exp_dir: "/root/efficient_dl/unet-infer-optimization/experiments/quantization_2026_04_20"
model_path: "/root/efficient_dl/unet-infer-optimization/experiments/quantization_2026_04_20/lightning_logs/version_2/checkpoints/quantization_2026_04_20.ckpt"
model:
  classes: 3
  in_channels: 3
  encoder_weights: "imagenet"
  encoder_name: "resnet34"

data:
  batch_size: 32
  input_size: 256
  num_workers: 4

bench:
  warmup: 20
  min_run_time: 3
