exp_dir: "/root/efficient_dl/unet-infer-optimization/experiments/quantization_2026_04_20"
model_path: "/root/efficient_dl/unet-infer-optimization/experiments/quantization_2026_04_20/lightning_logs/version_2/checkpoints/trained_baseline.ckpt"
model:
  classes: 3
  in_channels: 3
  encoder_weights: "imagenet"
  encoder_name: "resnet34"

data:
  batch_size: 1  # у меня только 5Gb на A100
  input_size: 256
  num_workers: 4

calibration:
  data_reader_limit: 2  # сколько батчей использовать для калибровки, для тестирования поставил 2

